url: "https://deploy-preview-150--systeme-conception-canada-ca.netlify.app/"
urldesigncanadaca: "https://deploy-preview-253--design-system-canada-ca.netlify.app"
urlcanadaca: "https://www.canada.ca"
urlblogca: "https://blogue.canada.ca"
