[context.deploy-preview]
    # Replace DEPLOY_PRIME_URL placeholder with actual Netlify preview URL
	command = "sed -i.bak 's|DEPLOY_PRIME_URL|'${DEPLOY_PRIME_URL}'|g' _config.staging.yml && bundle exec jekyll build --config _config.yml,_config.staging.yml"
